name: Test Tag Trigger

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag
        run: |
          echo "Tag triggered: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"